Remove //@ts-ignore in level-utils.ts, fix resulting error
Removes the //@ts-ignore comment introduced in commit:
b7a5cccfee28620cf06e0d2e0bf3391421793249

Reason is the linter throwing following error:
"Do not use "@ts-ignore" because it alters compilation errors
@typescript-eslint/ban-ts-comment"

After removing //@ts-ignore the following error occurs:
TS2345: Argument of type 'ILevel | undefined' is not assignable
to parameter of type 'ILevel'.   Type 'undefined' is not
assignable to type 'ILevel'.